#!/bin/bash
if [ "$EUID" -ne 0 ]; then
    echo "Require sudo privilege."
    exit 1
fi

config="/etc/profile"
if [ ! -f "$config" ]; then
  touch "$config"
fi

for path in "$@"; do 
    PATH=$PATH:$path    
done
echo "export PATH=\"$PATH\"" >> $config
source $config