#!/bin/bash
if [ "$EUID" -ne 0 ]; then
    echo "Require sudo privilege."
    exit 1
fi

config="/etc/profile"
if [ ! -f "$config" ]; then
  touch "$config"
fi

for arg in "$@"; do
    IFS=':' read -r name value <<< "$arg"
    
    if [ -z "$name" ] || [ -z "$value" ]; then
        echo "Invalid argument's format '$arg', which should be like name:value."
        continue
    fi

    echo "export $name=\"$value\"" >> $config
    echo "$name added to $(whoami) successfully."
done

source $config